version: '3.4'

services:
  edajavams:
    image: edajavams
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./java:/app