FROM openjdk:11.0.8
WORKDIR /app
# VOLUME /tmp
# ARG JAVA_OPTS
# ENV JAVA_OPTS=$JAVA_OPTS
# COPY edajavams.jar edajavams.jar
# EXPOSE 3000
# ENTRYPOINT exec java $JAVA_OPTS -jar edajavams.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar edajavams.jar
